export enum ActionType {
  IS_NETWORK_ERROR = 'IS_NETWORK_ERROR',
  IS_SERVER_ERROR = 'IS_SERVER_ERROR',
  IS_LOADING = 'IS_LOADING',
  RETRY = 'RETRY',
  USER_DETAILS = 'USER_DETAILS',
  LOG_OUT = 'LOG_OUT',
  ADD_TO_CART = 'ADD_TO_CART',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  SET_SPECIAL_FOOD = 'SET_SPECIAL_FOOD',
  SET_POPULAR_FOOD = 'SET_POPULAR_FOOD',
}
